name: Actions Sanity Check

on:
  push:
    branches: [ main ]

jobs:
  actions-sanity:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip || true
          pip install -r requirements.txt || true
      - name: Run Import Fixer
        run: |
          python fix_imports_simple.py || true
      - name: Debug Info
        run: |
          pwd || true
          ls -l || true
          python --version || true
      - name: Run NL Summary Generator
        run: |
          python run_nl_explain_and_fix.py
      - name: Echo Hello
        run: echo "If you see this, Actions is working." || true
      - name: Echo Hello
        run: echo "If you see this, Actions is working."
