name: CBMV Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  cbmv-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run Import Fixer
        run: |
          python fix_imports_simple.py || true

      - name: Run NL Summary Generator
        run: |
          python run_nl_explain_and_fix.py

      - name: Check for unmapped files or errors
        run: |
          if grep -q "Error: invalid syntax" all_module_nl_summaries.txt || grep -q "No docstring found" all_module_nl_summaries.txt; then
            echo "❌ Mapping failed: Syntax errors or missing docstrings detected!" && exit 1
          fi
          echo "✅ All files mapped and documented."

      - name: Upload Codebase Map Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: codebase_map_latest
          path: docs/codebase_map_latest.md

      - name: Upload NL Summaries Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: all_module_nl_summaries
          path: all_module_nl_summaries.txt
