name: CBMV Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  cbmv-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo Test
        run: echo "Hello from CBMV Test Workflow!"
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'
